@startuml
title "Backend Oauth 2.0 with Epic"
hide footbox
hide unlinked

autonumber "[0] "

box "User" #LightGreen
participant "Patient" as Patient << (U, #ccebc5) user >>
participant "Browser" as Browser << (U, #ccebc5) user >>
end box

box "Vidyo Components" #LightBlue
participant "Vidyo Epic Service" as VidyoEpicService << (C, #b3cde3) Vidyo >>
participant "Portal" as Portal << (C, #b3cde3) Vidyo >>
participant "Portal Database/Query Parameter Service" as PortalDB << (C, #b3cde3) Vidyo >>
participant "VidyoConnect App" as VidyoConnect << (C, #b3cde3  ) Vidyo >>
end box

box "Epic Components" #LightCoral
participant "Epic App Orchard" as EPIC << (E, #fbb4ae) EPIC >>
participant "Epic Web Service" as EPS << (E, #fbb4ae) EPIC >>
end box

==Register Backend Service with Epic App Orchard==
VidyoEpicService->VidyoEpicService: generate **{publicKey, privateKey}**
VidyoEpicService<->EPIC : register backed app with **clientID, publicKey**
==Get backend service access token==
VidyoEpicService->VidyoEpicService : generate **JWT** containing **clientID** \n signed with **privateKey**
VidyoEpicService->EPS : exchange **JWT** for **backendServiceAccessToken** 
EPS->EPS : validate **JWT**
VidyoEpicService<--EPS : return **backendServiceAccessToken**
VidyoEpicService->VidyoEpicService : cache **backendServiceAccessToken**
==Using the backendServiceAccessToken==
VidyoEpicService->EPS : use **backendServiceAccessToken** \nfor calling **GetTelehealthDirectLaunchToken()**
@enduml